- name: Copy mongodb repo file
  ansible.builtin.copy:
     src: mongo.repo
     dest: /etc/yum.repos.d/mongo.repo


- name: Install mongodb client
  ansible.builtin.dnf:
    name: mongodb-mongosh
    state: latest

- name: Load Master data
  ansible.built.in.shell: mongosh --host mongo.dev.naifah.online </app/db/master-data.js

